%YAML 1.1
---
sources:
  # Class cls cl
  - { id: B0D1973, tit: Баян, sub: Підготовча група,
      aut: [О. Денисов], pub: Музична Україна, year: 1973 }
  - { id: B0DU1982, tit: Баян, sub: Підготовча група,
      aut: [О. Денисов, В. Угринович], pub: Музична Україна, year: 1982 }
  - { id: B1AK1979, tit: Баян, sub: 1 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, year: 1979 }
  - { id: B1AK1985, tit: Баян, sub: 1 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, year: 1985 }
  - { id: B2AK1979, tit: Баян, sub: 2 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, year: 1979 }
  - { id: B2AK1987, tit: Баян, sub: 2 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, year: 1987 }
  - { id: FBB1BZ1980, tit: Виборний баян, sub: 1 клас,
      aut: [В. Бесфамільнов, А. Зубарев], pub: Музична Україна, year: 1980 }
  - { id: FBB2BZ1981, tit: Виборний баян, sub: 2 клас,
      aut: [В. Бесфамільнов, А. Зубарев], pub: Музична Україна, year: 1981 }
  - { id: FBB3BZ1982, tit: Виборний баян, sub: 3 клас,
      aut: [В. Бесфамільнов, А. Зубарев], pub: Музична Україна, year: 1982 }
  # Tutorial tut tu
  - { id: BTBC1936, tit: Самоучитель игры на баяне,
      aut: [А. Басурманов, Н. Чайкин], pub: Советский композитор, year: 1936 }
  - { id: BTB1978, tit: Самоучитель игры на баяне,
      aut: [А. Басурманов], pub: Советский композитор, year: 1978 }
  - { id: BTB1989, tit: Самоучитель игры на баяне,
      aut: [А. Басурманов], pub: Советский композитор, year: 1989 }
  # School sch sc
  - { id: FBBSC1978, tit: Школа гри на виборному баяні, # p. 140 TODO
      aut: [С. Чапкій], pub: Музична Україна, year: 1978 }
  - { id: BSA1983, tit: Школа игры на баяне,
      aut: [Ю. Акимов], pub: Советский композитор, year: 1983 }
  - { id: PBS1AG1970, tit: Прогрессивная школа игры на баяне, sub: Часть 1,
      aut: [Ю. Акимов, П. Гвоздев], pub: Советский композитор, year: 1970 }
  - { id: PBS2A1976, tit: Прогрессивная школа игры на баяне, sub: Часть 2,
      aut: [Ю. Акимов], pub: Советский композитор, year: 1976 }
  - { id: BSN1985, tit: Школа игры на готово-выборном баяне, # p. 125 TODO
      aut: [В. Накапкин], pub: Советский композитор, year: 1985 }
  - { id: BSO1981, tit: Школа игры на баяне,
      aut: [А. Онегин], pub: Музыка, year: 1981 }
  - { id: FBBMS4NP1974, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 4,
      aut: [В. Накапкин, В. Платонов], pub: Советский композитор, year: 1974 }
  - { id: FBBMS5T1974, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 5,
      aut: [А. Толмачев], pub: Советский композитор, year: 1974 }
  - { id: FBBMS6N1975, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 6,
      aut: [В. Накапкин], pub: Советский композитор, year: 1975 }
  - { id: FBBMS7PT1975, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 7,
      aut: [В. Платонов, А. Толмачев], pub: Советский композитор, year: 1975 }
  - { id: FBBMS8N1976, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 8,
      aut: [В. Накапкин], pub: Советский композитор, year: 1976 }
  - { id: FBBMS9P1976, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 9,
      aut: [В. Платонов], pub: Советский композитор, year: 1976 }
  - { id: FBBMS10N1977, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 10,
      aut: [В. Накапкин], pub: Советский композитор, year: 1977 }
  - { id: FBBMS11P1977, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 11,
      aut: [В. Платонов], pub: Советский композитор, year: 1977 }
  - { id: FBBMS12N1978, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 12,
      aut: [В. Накапкин], pub: Советский композитор, year: 1978 }
  - { id: FBBMS13P1978, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 13,
      aut: [В. Платонов], pub: Советский композитор, year: 1978 }
  - { id: FBBMS14N1979, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 14,
      aut: [В. Накапкин], pub: Советский композитор, year: 1979 }
  - { id: FBBMS15P1979, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 15,
      aut: [В. Платонов], pub: Советский композитор, year: 1979 }
  - { id: FBBMS16N1980, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 16,
      aut: [В. Накапкин], pub: Советский композитор, year: 1980 }
  - { id: FBBMS17P1980, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 17,
      aut: [В. Платонов], pub: Советский композитор, year: 1980 }
  - { id: FBBMS19N1981, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 19,
      aut: [В. Накапкин], pub: Советский композитор, year: 1981 }
  - { id: FBBMS20P1981, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 20,
      aut: [В. Платонов], pub: Советский композитор, year: 1981 }
  - { id: FBBMS21N1982, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 21,
      aut: [В. Накапкин], pub: Советский композитор, year: 1982 }
  - { id: FBBMS22P1982, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 22,
      aut: [В. Платонов], pub: Советский композитор, year: 1982 }
  - { id: FBBMS23T1982, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 23,
      aut: [А. Толмачев], pub: Советский композитор, year: 1982 }
  - { id: FBBMS24N1983, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 24,
      aut: [В. Накапкин], pub: Советский композитор, year: 1983 }
  - { id: FBBMS25P1983, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 25,
      aut: [В. Платонов], pub: Советский композитор, year: 1983 }
  - { id: FBBMS26N1983, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 26,
      aut: [І. Назаренко], pub: Советский композитор, year: 1983 }
  - { id: FBBMS27N1984, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 27,
      aut: [Г. Никитин], pub: Советский композитор, year: 1984 }
  - { id: FBBMS28P1984, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 28,
      aut: [В. Платонов], pub: Советский композитор, year: 1984 }
  - { id: FBBMS29P1985, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 29,
      aut: [В. Платонов], pub: Советский композитор, year: 1985 }
  - { id: FBBMS30N1985, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 30,
      aut: [В. Накапкин], pub: Советский композитор, year: 1985 }
  - { id: FBBMS31N1986, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 31,
      aut: [В. Накапкин], pub: Советский композитор, year: 1986 }
  - { id: FBBMS32P1986, tit: Готово-выборный баян в музыкальной школе, sub: Выпуск 32,
      aut: [В. Платонов], pub: Советский композитор, year: 1986 }
  # Course crs cr
  - { id: TYBC1B1970, tit: Трехгодичный курс обучения игры на баяне, sub: Часть 1,
      aut: [А. Басурманов], pub: Советский композитор, year: 1970 }
  - { id: TYBC2B1971, tit: Трехгодичный курс обучения игры на баяне, sub: Часть 2,
      aut: [А. Басурманов], pub: Советский композитор, year: 1971 }
  - { id: CLFBBS1979, tit: Пособие для начального обучения игры на готово-выборном баяне,
      aut: [А. Сурков], pub: Советский композитор, year: 1979 }
  # Study stu st
  - { id: SB1NU1979, tit: Етюди для баяна на різні види техніки, sub: 1 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, year: 1979 }
  - { id: SB2NU1977, tit: Етюди для баяна на різні види техніки, sub: 2 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, year: 1977 }
  - { id: SB3NU1979, tit: Етюди для баяна на різні види техніки, sub: 3 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, year: 1979 }
  - { id: SB4NU1978, tit: Етюди для баяна на різні види техніки, sub: 4 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, year: 1978 }
  - { id: SB5NU1980, tit: Етюди для баяна на різні види техніки, sub: 5 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, year: 1980 }
  # Collection col co
  - { id: UFSFBR1978, tit: Українські народні пісні, sub: в перекладенні для баяна,
      aut: [М. Різоль], pub: Музична Україна, year: 1978 }
  # Lyrics lyr ly
  - { id: IIDBF2021, tit: "Іди, іди, дощику",
      sub: "Пісні для дітей 1–4 класів у супроводі баяна",
      aut: [О. Бубнов, Н. Філіпчук], pub: Тернопіль Богдан, year: 2021 }
  - { id: OZGGP1993, tit: "Ой за гаєм, гаєм",
      sub: "Українські народні пісні в легкій обробці для фортепіано",
      aut: [Н. Петілкіна], pub: Музична Україна, year: 1993 }
